# Generated by Django 2.0 on 2017-12-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171209_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truecallerdata',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
