# Generated by Django 2.0 on 2017-12-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171209_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDITips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tips', models.TextField()),
            ],
        ),
    ]
